array_width = 100
attr_fn_like_width = 100
chain_width = 100
edition = "2021"
fn_params_layout = "Tall"
fn_call_width = 100
hard_tabs = true
match_block_trailing_comma = true
max_width = 100
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 100
single_line_if_else_max_width = 100
struct_lit_width = 100
struct_variant_width = 100
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
