name: Publishing

on:
  release:
    types: [released]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo publish --token ${TOKEN}
      env:
        TOKEN: ${{ secrets.PUBLISH_TOKEN }}
